### ISSUE TITLE
parseGraphQLHTTP is not a function

### ISSUE THREAD

**Issue by tsvetann** [thebakeryio/parse-graphql-server#1]
Hi,

I followed your example to setup parseGraphQLHTTP but I get the following error:

`TypeError: parseGraphQLHTTP is not a function`

My code:
```
const parseGraphQLHTTP = require('parse-graphql-server');
....

app.use('/graphql', cors(corsOptions), parseGraphQLHTTP({
  schema: schema,
  graphiql: true
}));
```

**Comment by callmephilip** [comment]
looks like an issue with how the function is exposed in the module (using export default). if you inspect `parseGraphQLHTTP`, you will see it actually looks like this  `{ default: [Function: setup] }`.

so you currently have 2 options:

1. Use the `import` statement just like in the example: 
`import parseGraphQLHTTP from 'parse-graphql-server'`

2. Stick to require with an added twist: 
`const parseGraphQLHTTP = require('parse-graphql-server').default;`

I need to figure out how to update the transpiler settings to make the module compatible with the vanila require API

**Comment by tsvetann** [comment]
Point 2 works for me. Thanks for the blazing fast response. It would be nice if this can be fixed
